// <auto-generated />
using System;
using Animal_Shelter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Animal_Shelter.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    [Migration("20240228122343_AddAnimalsAndAnimalSheltersTables")]
    partial class AddAnimalsAndAnimalSheltersTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Animal_Shelter.Entities.AnimalShelter", b =>
                {
                    b.Property<int>("AnimalShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalShelterId"));

                    b.Property<string>("AnimalShelterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalShelterId");

                    b.ToTable("AnimalShelters");
                });

            modelBuilder.Entity("Animal_Shelter.Entities.Animals", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("AnimalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnimalShelterNameAnimalShelterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.HasIndex("AnimalShelterNameAnimalShelterId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Animal_Shelter.Entities.Animals", b =>
                {
                    b.HasOne("Animal_Shelter.Entities.AnimalShelter", "AnimalShelterName")
                        .WithMany()
                        .HasForeignKey("AnimalShelterNameAnimalShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalShelterName");
                });
#pragma warning restore 612, 618
        }
    }
}
