name: CI

on:
  push:
    branches: [ "master", "maciek-temp" ]
  pull_request:
    branches: [ "master", "CI-tests" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        env:
          CI: true
          AUTH_JWT_ISSUER: ${{ secrets.AUTH_JWT_ISSUER }}
          AUTH_JWT_DATE: ${{ secrets.AUTH_JWT_DATE }}
          AUTH_JWT_KEY: ${{ secrets.AUTH_JWT_KEY }}
        run: dotnet test --no-build --verbosity normal
  
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Super-Linter
      uses: super-linter/super-linter@v5.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
