name: Format C# and YAML files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format for AnimalShelter folder
        run: dotnet format --check "Animal-Shelter_B/Animal_Shelter/AnimalShelter.csproj"
        continue-on-error: true

      - name: Run dotnet-format for AnimalShelterTests folder
        run: dotnet format --check "Animal-Shelter_B/AnimalShelterTests/AnimalShelterTests.csproj"
        continue-on-error: true

      - name: Check for changes
        id: git-check
        run: echo ::set-output name=changed::$(git status --porcelain)
        shell: bash

      - name: Commit changes (if any)
        if: steps.git-check.outputs.changed != ''
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Apply code formatting"
          git push
      
