name: Format C# and YAML files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet format --check
        continue-on-error: true

      - name: Check for changes
        id: git-check
        run: echo ::set-output name=changed::$(git status --porcelain)
        shell: bash

      - name: Commit changes (if any)
        if: steps.git-check.outputs.changed != ''
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Apply code formatting"
          git push
      - name: Test
        env:
          CI: true
          AUTH_JWT_ISSUER: ${{ secrets.AUTH_JWT_ISSUER }}
          AUTH_JWT_DATE: ${{ secrets.AUTH_JWT_DATE }}
          AUTH_JWT_KEY: ${{ secrets.AUTH_JWT_KEY }}
        run: dotnet test --no-build --verbosity normal
