---
name: Lint

on:
  push:
    branches: [ "maciek-temp"]
  pull_request: 
    branches: [ "maciek-temp"]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .NET Lint
        uses: zyactions/dotnet-lint@v1
        with:
          workspace: test
          implicit-restore: true