---
name: Lint

on:
  push:
    branches: [ "maciek-temp"]
  pull_request:
    branches: [ "maciek-temp"]

permissions: { }

jobs:
  lint:
    permissions:
      contents: read
      packages: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Super-Linter
        uses: super-linter/super-linter@v6.3.1
        env:
          DEFAULT_BRANCH: maciek-temp
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          GI